### ISSUE TITLE
Bugs/issues when creating choropleth map from shapefile 

### ISSUE THREAD

**Issue by pkmn99** [ioam/geoviews#62] opened 2017-04-18 19:47 UTC
I have some bugs/issues when creating maps from shapefile. 
Here I use the UK referendum as an example to reproduce these issues. 

(1) If there are missing values, the corresponding spatial unit on the map will not be displayed. it would be better to have an option to automatically fill the missing value to display all the spatial unit even though they don't . 
![case2](https://cloud.githubusercontent.com/assets/17201113/25149251/606c0812-2443-11e7-96cf-ab54e5258dee.png)

(2)If the data type is integer. The map will not show color correctly.
![case1](https://cloud.githubusercontent.com/assets/17201113/25149217/4a9b6fa0-2443-11e7-9189-efa138bdf92a.png)

(3) When the data value contains nan, the map looks good. But when these nan values are filled by 0. the resulting map is totally incorrect. (Here I manually assign three nan and fill them by zero)
![case3](https://cloud.githubusercontent.com/assets/17201113/25149259/672960b4-2443-11e7-93eb-4dc3df68bcc8.png)

(4) Latitude and longitude on the map also seem to be problematic.  
![case3](https://cloud.githubusercontent.com/assets/17201113/25149865/89d23a8a-2445-11e7-9a92-822f2abb90d4.png)

(5) Better to have way to set color range for these maps. 
I am affected mostly by the third issue, because in my study I have to fill some values, otherwise it will become the first issue. 

Hope these issues can be fixed or improved.

Code to reproduce these issues is attached. I don't know how to upload jupyter notebook.
```
import pandas as pd
import numpy as np
import holoviews as hv
import geoviews as gv
import cartopy
from cartopy import crs as ccrs
%pylab

hv.notebook_extension('bokeh','matplotlib')

shapefile = 'boundaries/boundaries.shp'
shapes = cartopy.io.shapereader.Reader(shapefile)

referendum = pd.read_csv('referendum.csv')
referendum['value1'] = referendum['leaveVoteshare']

%%output backend='bokeh'
%%opts Shape (cmap='viridis') [xaxis=None yaxis=None tools=['hover'] width=400 height=500]

# Case 1: set referendum value is interger
referendum_modified = referendum.copy()
referendum_modified['value1'] = referendum_modified['value1'].apply(np.int)

data = hv.Dataset(referendum_modified)

gv.Shape.from_records(shapes.records(), data, on='code', value='value1',
                     index=['name', 'regionName'], crs=ccrs.PlateCarree())

%%output backend='bokeh'
%%opts Shape (cmap='viridis') [xaxis=None yaxis=None tools=['hover'] width=400 height=500]

# Case 2: If referendem values are missing for some counties
referendum_modified = referendum.copy()

referendum_modified = referendum_modified.iloc[0:100,:]

data = hv.Dataset(referendum_modified)

gv.Shape.from_records(shapes.records(), data, on='code', value='value1',
                     index=['name', 'regionName'], crs=ccrs.PlateCarree())

%%output backend='bokeh'
%%opts Shape (cmap='viridis') [xaxis=None yaxis=None tools=['hover'] width=400 height=500]

# Case 3: Here set the fist three rows to nan and fill them with 0   
referendum_modified = referendum.copy()
referendum_modified['value1'][0:3]=np.nan
referendum_modified['value1'] = referendum_modified['value1'].fillna(0)

data = hv.Dataset(referendum_modified)

    
gv.Shape.from_records(shapes.records(), data, on='code', value='value1',
                     index=['name', 'regionName'], crs=ccrs.PlateCarree())
```

**Comment by philippjfr** [comment] 2017-04-18 21:44
I'm currently suspecting/hoping these issues have already been fixed. Could you please provide the output of:

print(gv.__version__)
print(hv.__version__)

**Comment by pkmn99** [comment] 2017-04-18 22:05
Here is the vesion info:
hv : 1.6.2-1509-g1b94bfdc
gv : 1.1.0

**Comment by philippjfr** [comment] 2017-04-18 22:09
Okay so that's pretty recent. Thanks for the detailed bug report I'm looking into it now.

**Comment by philippjfr** [comment] 2017-04-18 22:12
Btw to set color ranges simply use ``redim``. 

```python
choropleth = gv.Shape.from_records(shapes.records(), data, on='code', value='value1',
                     index=['name', 'regionName'], crs=ccrs.PlateCarree())
choropleth.redim(value1=dict(range=(0, 100)))
```

If you pull the latest master on holoviews you can even do ``choropleth.redim.range(value1=(0, 100))``.

**Comment by philippjfr** [comment] 2017-04-18 22:14
Your issue (4) should be addressed when https://github.com/ioam/geoviews/issues/36 is implemented, which seems in sight.

**Comment by pkmn99** [comment] 2017-04-18 22:32
Thanks for the redim method.  
I am not sure issue (4) is entirely due to bokeh.
Because if you directly display UK shapefile using bokeh, but without linking it to data value, you can get correct  latitude/longitude label. 
```
gv.Shape.from_records(shapes.records())
```
![bokeh_plot](https://cloud.githubusercontent.com/assets/17201113/25155836/ce0615ca-245c-11e7-9cc9-62809a359814.png)

So I suspect something is wrong when you link shapefile to data value.

**Comment by philippjfr** [comment] 2017-04-18 22:39
>Because if you directly display UK shapefile using bokeh, but without linking it to data value, you can get correct latitude/longitude label.

That's not the data value but this bit which specifies the projection ``crs=ccrs.PlateCarree())``. If your data is already in lat/lons you don't really need to provide it. The crs simply ensures the data can be projected to Mercator and therefore be overlaid onto a bokeh tilesource.

**Comment by pkmn99** [comment] 2017-04-18 22:41
I also would like to try the latest 1.20dev version to see if these issues haven been resolved but unfortunately I can't it installed using: conda install -c ioam geoviews=1.2.0dev1. So I have to stay with the 1.10 version.

**Comment by philippjfr** [comment] 2017-04-18 22:43
>I also would like to try the latest 1.20dev version to see if these issues haven been resolved but unfortunately I can't it installed using: conda install -c ioam geoviews=1.2.0dev1. So I have to stay with the 1.10 version.

I'll try to cut a 1.2.0dev2 release tomorrow.

**Comment by philippjfr** [comment] 2017-04-18 23:17
Okay it appears some of it was already fixed but I'm shortly going to make a PR with some further fixes. One of the main issues here is that our format for storing this kind of data along with value dimensions is fairly inflexible and inefficient, there's plans on improving how we store data like this at which point this will become far easier (and faster). For now your condition (1) it has to add an additional Index dimension because with missing values it has to be able to index items uniquely.

Otherwise it all works now:

### 1. Integer values

<img width="411" alt="screen shot 2017-04-19 at 12 07 58 am" src="https://cloud.githubusercontent.com/assets/1550771/25156889/7d653b44-2495-11e7-9195-4cddf8481c2f.png">

### 2. Missing counties

<img width="408" alt="screen shot 2017-04-19 at 12 08 06 am" src="https://cloud.githubusercontent.com/assets/1550771/25156892/83ad135a-2495-11e7-9c87-74a7cc79e010.png">

### 3. NaN values

<img width="414" alt="screen shot 2017-04-19 at 12 08 13 am" src="https://cloud.githubusercontent.com/assets/1550771/25156895/8adb9f5c-2495-11e7-952b-e8d8b6ac0107.png">

**Comment by pkmn99** [comment] 2017-04-18 23:27
Very glad hear back from you with most of the issues fixed so quickly. You guys are awesome! 
I think issue 1 will not bother me too much as long as the nan issue has been fixed. 
Are you saying there will be a new version released tomorrow with these issues fixed? 
I am looking forward to it.
Thanks!

**Comment by philippjfr** [comment] 2017-04-18 23:32
>You guys are awesome!

Glad you're enjoying the library.

>Are you saying there will be a new version released tomorrow with these issues fixed?

A dev release yes, we're gearing up to a general holoviews release this week and an official geoviews release will follow shortly after.

**Comment by philippjfr** [comment] 2017-04-18 23:42
Btw you could try this now: ``conda install -c ioam/label/dev geoviews=1.2.0dev1``, it might include some of the color fixes, but won't include my changes in https://github.com/ioam/geoviews/pull/63 yet.

**Comment by pkmn99** [comment] 2017-04-18 23:48
The install command from you works! Now I can update geoviews. I will also try the next dev version. Thank you very much!

**Comment by dtelliott79** [comment] 2017-04-25 20:45
I had bookmarked this thread last week, being that I was having problems with some of the same bugs. However, now that I installed 0.12.0dev1, I'm getting an error:

    AttributeError: 'GeoShapePlot' object has no attribute '_get_colormapper'

in code that was working before the update. How difficult would it be for me to uninstall the update? And more importantly, when might the next full releases fixing these bugs be out? Just so I known when to check back.

**Comment by philippjfr** [comment] 2017-04-25 20:51
>How difficult would it be for me to uninstall the update? And more importantly, when might the next full releases fixing these bugs be out? Just so I known when to check back.

I suspect the issue is that you're still on HoloViews 1.6.2. We are releasing HoloViews 1.7 this very minute and that should fix your problems. Just wait another half an hour or so and then run:

```
conda install -c ioam holoviews
```

I'll also be releasing GeoViews 1.2.0 later this week with some further fixes.

**Comment by philippjfr** [comment] 2017-04-26 01:43
Both HoloViews 1.7.0 and GeoViews 1.2.0 are now released, please update with:

    conda install -c ioam -c conda-forge holoviews geoviews

I'll close this issue but please feel free to reopen it if you encounter further issues.

**Closed by philippjfr** 2017-04-26 01:43 UTC

**Comment by pkmn99** [comment] 2017-04-26 15:21
Great job! I updated both holoviews and geoviews and most issues have been resolved.
It seems there is a new issue with NaN value in the new version. In previous version, we can get correct map even the data contains NaN, but in the new version, NaN values cause errors. 
For example, when comment out fillna, the error occurs.
`referendum_modified['value1'] = referendum_modified['value1'].fillna(0)`

**Comment by pkmn99** [comment] 2017-04-26 16:46
(1) It is good to have counties with missing values to show up on the map (previous issue 1) in the 1.20 version. Is there an option to disable this automatic fill? 

(2) Is there a way to set the extent of the map by lat/lon? For example, if we want the map to display Southern part of UK instead of the entire UK. We could modify the shapefile to have a Southern subset but I think there should be a better way than that. 

Thanks!
