### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by pingyangtiaer** [ioam/geoviews#119] opened 2018-01-10 18:02 UTC
I installed the geoviews library using the following commands (), the installation showed successfully, however, when I tried to import it into python, I got error:

(C:\Anaconda2) c:\Anaconda2>python.exe
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:34:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import geoviews
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Anaconda2\lib\site-packages\geoviews\__init__.py", line 9, in <module>
    from .element import (_Element, Feature, Tiles,     # noqa (API import)
  File "c:\Anaconda2\lib\site-packages\geoviews\element\__init__.py", line 3, in <module>
    from .geo import (_Element, Feature, Tiles, is_geographic,     # noqa (API import)
  File "c:\Anaconda2\lib\site-packages\geoviews\element\geo.py", line 5, in <module>
    from cartopy.io.img_tiles import GoogleTiles as cGoogleTiles
  File "c:\Anaconda2\lib\site-packages\cartopy\io\img_tiles.py", line 32, in <module>
    from PIL import Image
  File "c:\Anaconda2\lib\site-packages\PIL\Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.

Is geoviews not compitable with Python2.7.14 on windows?
Looking forward to hearing from you.
Thanks,

**Comment by jbednar** [comment] 2018-01-10 18:26
I think this is a duplicate of https://github.com/ioam/geoviews/issues/117 ; there are problems with the PIL library that we import, but they can be worked around as described in that issue, or you can wait for the next release (should be soon, but not today!) that should declare which PIL versions are working.

**Closed** 2018-01-10 18:27 UTC
