### ISSUE TITLE
holoviews/geoviews notebook extension problem

### ISSUE THREAD

**Issue by khannaum** [ioam/geoviews#44] opened 2016-12-27 04:41 UTC
### When notebook extension is matplotlib values in holoviews table changes on selection
![image](https://cloud.githubusercontent.com/assets/7712413/21490499/f87361d0-cc16-11e6-993d-94e1562fd024.png)

### When notebook extension is bokeh and matplotlib, values in holoviews table does not changes and only geoviews points values changes . Help required  holoviews table and geoviews points values both changes upon selection.

![image](https://cloud.githubusercontent.com/assets/7712413/21490682/84a5f5fe-cc18-11e6-82f6-524311cee509.png)

**Comment by philippjfr** [comment] 2016-12-27 12:55
Closing as duplicate of https://github.com/ioam/holoviews/issues/1028, since ``Table`` is a holoviews element.

**Closed by philippjfr** 2016-12-27 12:55 UTC
